# Generated by Django 5.0.2 on 2024-03-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='itemsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('tax', models.FloatField()),
                ('img', models.CharField(max_length=150)),
                ('total', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('itemsId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phone.items')),
            ],
        ),
    ]
