# Generated by Django 4.2.10 on 2024-03-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('net', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('itemsDetailsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.itemsdetails')),
            ],
        ),
    ]
